FROM kong:2.6.0-alpine

ARG MINHA_VARIAVEL
ARG OUTRA_VARIAVEL

ENV MINHA_VARIAVEL $MINHA_VARIAVEL
ENV OUTRA_VARIAVEL $OUTRA_VARIAVEL

RUN echo "Minha variável é: $MINHA_VARIAVEL"
RUN echo "Outra variável é: $OUTRA_VARIAVEL"
